const data = {
  product: [
    {
      name: "TERENCE эрэгтэй куртка",
      slug: "eregtei-kurtik",
      category: "Гадуур хувцас",
      image: "/images/1.jpeg",
      price: 250000,
      brand: "Terence",
      rating: 4.5,
      numReviews: 8,
      countInStock: 13,
      description: "Гадуур хүрэм куртка",
    },
    {
      name: "Эрэгтэй куртка",
      slug: "eregtei-kurtik2",
      category: "Гадуур хувцас",
      image: "/images/2.jpeg",
      price: 150000,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 13,
      description: "Гадуур хүрэм куртка",
    },
    {
      name: "Эрэгтэй курткаЭрэгтэй курткаЭрэгтэй курткаЭрэгтэй куртка",
      slug: "eregtei-kurtik3",
      category: "Гадуур хувцас",
      image: "/images/3.jpeg",
      price: 285000,
      brand: "Terence",
      rating: 4.5,
      numReviews: 8,
      countInStock: 3,
      description: "Гадуур хүрэм куртка",
    },
    {
      name: "Өвлийн куртка",
      slug: "eregtei-kurtik4",
      category: "Гадуур хувцас",
      image: "/images/4.jpeg",
      price: 450000,
      brand: "Terence",
      rating: 4.5,
      numReviews: 8,
      countInStock: 13,
      description: "Гадуур хүрэм куртка",
    },
    {
      name: "TERENCE эрэгтэй куртка",
      slug: "eregtei-kurtik5",
      category: "Гадуур хувцас",
      image: "/images/5.jpeg",
      price: 250000,
      brand: "Terence",
      rating: 4.5,
      numReviews: 8,
      countInStock: 13,
      description: "Гадуур хүрэм куртка",
    },
    {
      name: "TERENCE эрэгтэй куртка",
      slug: "eregtei-kurtik6",
      category: "Гадуур хувцас",
      image: "/images/6.jpeg",
      price: 250000,
      brand: "Terence",
      rating: 4.5,
      numReviews: 8,
      countInStock: 31,
      description: "Гадуур хүрэм куртка",
    },
  ],
};

export default data;
