const data = {
  product: [
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
    {
      name: "ХАЙРЦАГТАЙ САРНАЙ САРНАЙ /204/",
      slug: "ХАЙРЦАГТАЙ-САРНАЙ",
      category: "Гадуур хувцас",
      image: "/images/1.png",
      price: 210000,
      rating: 4.5,
      countInStock: 13,
    },
  ],
};

export default data;
